-- SQLite


--DROP TABLE DESTINATIONS;

/*CREATE TABLE IF NOT EXISTS BUS(
bus_id INTEGER PRIMARY KEY ,
destin TEXT,
ETA REAL,
GPS_LAT REAL,
GPS_LONG REAL
);*/



CREATE TABLE IF NOT EXISTS USER(
USER_ID INTEGER PRIMARY KEY ,
USERNAME TEXT,
PASSWORD TEXT
);


INSERT INTO USER (USER_ID,USERNAME,PASSWORD) VALUES(1,"1","1")
ON CONFLICT(USER_ID) DO UPDATE SET
USERNAME=excluded.USERNAME,
PASSWORD=excluded.PASSWORD
;
UPDATE STATIONS SET (GPS_LAT,GPS_LONG)=(36.810537,10.15354) WHERE STATIONS.DEST="CENTRALE B";

INSERT INTO BUS (BUS_ID,DEST)
        VALUES (2,"CENTRALE C")
        ON CONFLICT(BUS_ID) DO UPDATE SET 
        DEST=excluded.DEST
        ;
/*INSERT INTO BUS (BUS_ID,ROUTE,DISTANCE,ETA)
        VALUES (1,ROUTE,DISTANCE,ETA)
        ON CONFLICT(BUS_ID) DO UPDATE SET 
        ROUTE=excluded.ROUTE,
        DISTANCE=excluded.DISTANCE,
        ETA=excluded.ETA;*/
    




CREATE TABLE IF NOT EXISTS DESTINATIONS(
        DEST TEXT PRIMARY KEY,
        GPS_LAT REAL,
        GPS_LONG REAL
        );


/*INSERT INTO DESTINATIONS(DEST,GPS_LAT,GPS_LONG) VALUES("CENTRALE C",36.8393802, 10.204810)
        ON CONFLICT(DEST) DO UPDATE SET
        GPS_LAT = excluded.GPS_LAT,
        GPS_LONG = excluded.GPS_LONG;*/
                                        






CREATE TABLE IF NOT EXISTS FIXTURES(
BUS_ID INTEGER,
DEST TEXT)
;

UPDATE BUS SET DEST="CENTRALE A" WHERE BUS_ID=1;
DELETE FROM FIXTURES WHERE BUS_ID IN(1,2,3);
INSERT INTO FIXTURES (BUS_ID,DEST) VALUES (2,"CENTRALE C"),(1,"CENTRALE B") ,(3,"CENTRALE A"),(2,"CENTRALE A"), (1,"CENTRAL C") ,(1,"CENTRALE A");




/*UPDATE bus
SET dest = (
  SELECT f.dest
  FROM fixtures f
  WHERE f.bus_id = bus.bus_id
  ORDER BY f.rowid ASC
  LIMIT 1
);
*/

/*SELECT * FROM
BUS WHERE BUS.DEST= (
SELECT f.dest
FROM fixtures f
  WHERE f.BUS_ID = 1
  ORDER BY f.rowid ASC
  LIMIT 1
);*/


/*UPDATE BUS
SET DEST = (
    SELECT FIXTURES.DEST
    FROM FIXTURES
    WHERE FIXTURES.BUS_ID = 1
    ORDER BY FIXTURES.rowid ASC
    LIMIT 1
)
WHERE BUS.BUS_ID=1;

DELETE FROM FIXTURES 
WHERE rowid IN (
    SELECT rowid FROM FIXTURES 
    WHERE FIXTURES.BUS_ID = 1
    ORDER BY rowid ASC 
    LIMIT 1
);

/*SELECT * FROM BUS;
SELECT * FROM DESTINATIONS;*/


/*SELECT ETA,ROUTE FROM BUS WHERE DEST="CENTRALE A" ORDER BY ETA ASC;

INSERT INTO BUS (bus_id, GPS_LAT, GPS_LONG)
VALUES (2, 5, 56)
ON CONFLICT(bus_id) DO UPDATE SET 
GPS_LAT = excluded.GPS_LAT,
GPS_LONG = excluded.GPS_LONG
;

/*SELECT * FROM FIXTURES 
WHERE FIXTURES.BUS_ID = 2
ORDER BY rowid ASC
LIMIT 1;
*/

